登录支持https，账号密码通过body传输
nacos-group/nacos-sdk-go pull request #113
Opened 2020-09-09 01:40 UTC by holdno

2020-09-09 01:41 UTC, holdno commented
登录支持https，账号密码通过body传输，通过url query传输，可能导致密码泄露

2020-09-09 13:41 UTC, sanxun0325 commented
@holdno pr没什么问题,可以解决一下ci的错误.

2020-09-10 02:15 UTC, sanxun0325 requested changes
pr没什么问题,可以解决一下ci的错误.

2020-09-13 08:30 UTC, sanxun0325 approved these changes

2020-09-13 08:30 UTC, sanxun0325 commented
Thank you for your submission.Pr has been merged.

2020-09-13 08:30 UTC, merged