154 client factory params change to options
nacos-group/nacos-sdk-go pull request #171
Opened 2020-12-28 03:29 UTC by legenove

client create with options.

2021-01-03 08:33 UTC, lzp0412 approved these changes
LGTM

2021-01-05 10:51 UTC, sanxun0325 requested changes
对于创建客户端使用option方式，不够清晰和直接，可以考虑使用struct 来创建。

2021-01-05 12:19 UTC, legenove commented
> 对于创建客户端使用option方式，不够清晰和直接，可以考虑使用struct 来创建。

类似于RegisterInstance(param vo.RegisterInstanceParam)这种吗？

2021-01-05 13:18 UTC, sanxun0325 commented
> > 对于创建客户端使用option方式，不够清晰和直接，可以考虑使用struct 来创建。
> 
> 类似于RegisterInstance(param vo.RegisterInstanceParam)这种吗？
> 
> 例如：我创建一个参数struct
> 
> ```
> type NacosClientParam struct {
> 	clientConfig  constant.ClientConfig
> 	serverConfigs []constant.ServerConfig
> }
> ```
> 
> 这时候传入的时候，clientConfig就必须是必传的了，否则没有办法判空。
> 如果将设为引用：`clientConfig *constant.ClientConfig`， 这时候使用的话，就和之前的创建的参数不一致了。
> 这里要怎么处理呢？

clientConfig 不需要必须传，如果为nil，和原有逻辑一样提供默认参数。 这样改动比较小。

2021-01-06 06:47 UTC, legenove commented
> > > 对于创建客户端使用option方式，不够清晰和直接，可以考虑使用struct 来创建。
> > 
> > 
> > 类似于RegisterInstance(param vo.RegisterInstanceParam)这种吗？
> > 例如：我创建一个参数struct
> > ```
> > type NacosClientParam struct {
> > 	clientConfig  constant.ClientConfig
> > 	serverConfigs []constant.ServerConfig
> > }
> > ```
> > 
> > 
> > 这时候传入的时候，clientConfig就必须是必传的了，否则没有办法判空。
> > 如果将设为引用：`clientConfig *constant.ClientConfig`， 这时候使用的话，就和之前的创建的参数不一致了。
> > 这里要怎么处理呢？
> 
> clientConfig 不需要必须传，如果为nil，和原有逻辑一样提供默认参数。 这样改动比较小。

ok 已经完成，在vo中增加了Param
```
type NacosClientParam struct {
	clientConfig  *constant.ClientConfig
	serverConfigs []constant.ServerConfig
}
```

2021-01-08 02:13 UTC, sanxun0325 commented on clients/client_factory_test.go
> +func setConfigHistory(properties map[string]interface{}) (iClient nacos_client.INacosClient, err error) {
不需要这个func了。

2021-01-08 02:13 UTC, sanxun0325 commented on clients/client_factory_test.go
> +func TestSetConfigClient(t *testing.T) {
测试setConfig ，可以通过使用原有map方式构建出的client  对比 使用struct 构建出来的client 就可以了。

2021-01-08 02:13 UTC, sanxun0325 commented on example/service/main.go
> +	_, _ = clients.NewNamingClient(
example 中改成都使用 NewNamingClient 返回值的client 去调用吧。

2021-01-08 02:13 UTC, sanxun0325 commented on example/config/main.go
> +	_, _ = clients.NewConfigClient(
example 中改成都使用 NewConfigClient 返回值的client 去调用吧。

2021-01-08 07:00 UTC, legenove commented
done @sanxun0325

2021-01-13 06:52 UTC, sanxun0325 approved these changes
LGTM

2021-01-13 09:12 UTC, legenove commented
测试的结构改了确实更方便看了～学习了👍

2021-01-13 10:00 UTC, sanxun0325 commented
> 测试代码的结构改了后，确实更方便看了～学习了👍

大佬如果方便 可以加钉钉：wg46mjc 沟通交流

2021-01-14 01:45 UTC, lzp0412 approved these changes
LGTM

2021-01-14 05:28 UTC, merged