fix:修复windows文件名称问题
nacos-group/nacos-sdk-go pull request #205
Opened 2021-04-03 10:59 UTC by zhaoyunxing92

修复 https://github.com/nacos-group/nacos-sdk-go/issues/204 问题

2021-04-06 01:49 UTC, sanxun0325 requested changes

2021-04-06 01:49 UTC, sanxun0325 commented on clients/cache/disk_cache.go
> +		cacheKey = strings.ReplaceAll(cacheKey, ":", constant.WINDOWS_LEGAL_NAME_SPLITER)
文件名的设计是根据服务名group以及集群进行组合，即使包含特殊字符也并不会影响从cache读取服务信息。

2021-04-06 02:31 UTC, zhaoyunxing92 commented on clients/cache/disk_cache.go
> +		cacheKey = strings.ReplaceAll(cacheKey, ":", constant.WINDOWS_LEGAL_NAME_SPLITER)
windows上会创建不了缓存文件的

2021-04-07 14:21 UTC, zhaoyunxing92 commented on clients/cache/disk_cache.go
> +		cacheKey = strings.ReplaceAll(cacheKey, ":", constant.WINDOWS_LEGAL_NAME_SPLITER)
你这个测试不对吧使用`nacos@@providers:org.apache.dubbo.UserProvider:hangzhou`文件名测试

2021-04-08 01:49 UTC, sanxun0325 approved these changes
LGTM,thank you for your contribution.

2021-04-08 01:49 UTC, merged