当认证不通过时，创建client返 回成功(主要兼容nacos挂掉的情况)
nacos-group/nacos-sdk-go pull request #211
Opened 2021-04-15 13:57 UTC by legenove

#210

2021-04-15 14:07 UTC, legenove commented on common/nacos_server/nacos_server.go
> +	isLogin             bool
记录服务是否登录成功

2021-04-15 14:08 UTC, legenove commented on common/nacos_server/nacos_server.go
> +	// login when first login error
每次请求的时候，判断是否登录成功

2021-04-15 14:16 UTC, sanxun0325 requested changes

2021-04-15 14:16 UTC, sanxun0325 commented on common/nacos_server/nacos_server.go
> -		return &ns, err
只需要修改 当登录失败打印日志记录，不需要return就可以了。

2021-04-15 14:44 UTC, legenove commented on common/nacos_server/nacos_server.go
> -		return &ns, err
ok

2021-04-15 14:45 UTC, legenove commented on common/security/security_proxy.go
> +		tokenTtl:    3,  // default refresh token 3 second, if first login error
java那边默认是3秒，timer 默认是ac.tokenTtl-ac.tokenRefreshWindow = 3秒

2021-04-18 12:30 UTC, sanxun0325 commented on common/security/security_proxy.go
> +		tokenTtl:    3, // default refresh token 3 second, if first login error
![image](https://user-images.githubusercontent.com/28588342/115145593-f2871b80-a084-11eb-8990-2c3def6f926b.png)

2021-04-19 11:11 UTC, legenove commented on common/security/security_proxy.go
> +		tokenTtl:    3, // default refresh token 3 second, if first login error
好滴，我对java也不是特别熟，应该是看错了～改成了5秒

2021-04-19 15:12 UTC, sanxun0325 approved these changes
LGTM

2021-04-19 15:13 UTC, merged