Fixes #222, for the char is not urldecode
nacos-group/nacos-sdk-go pull request #224
Opened 2021-04-28 03:03 UTC by zhyc9de

经测试，`ListenConfig`timeout是因为获取配置后未urldecode

另外测试，dataId和group应该是不支持中文的，请问是否需要支持上

2021-05-26 15:13 UTC, sanxun0325 requested changes
非常不好意思，最近再忙2.0.0 。这个pr review的晚了一点，可以解决下CI中报的错误嘛

2021-05-31 09:04 UTC, zhyc9de commented
> 非常不好意思，最近再忙2.0.0 。这个pr review的晚了一点，可以解决下CI中报的错误嘛

看了下问题是vo目录没有测试文件，我感觉应该排除这个目录吧？你觉得如何处理比较好

2021-06-01 07:58 UTC, sanxun0325 commented
> > 非常不好意思，最近再忙2.0.0 。这个pr review的晚了一点，可以解决下CI中报的错误嘛
> 
> 看了下问题是vo目录没有测试文件，我感觉应该排除这个目录吧？你觉得如何处理比较好

可以本地跑一下，问题应该是出在config_client_test.go.

2021-06-21 15:16 UTC, sanxun0325 approved these changes
LGTM

2021-06-21 15:17 UTC, merged