use logger print log (#260)
nacos-group/nacos-sdk-go pull request #261
Opened 2021-06-09 03:32 UTC by x-lambda

2021-06-09 14:15 UTC, sanxun0325 requested changes

2021-06-09 14:15 UTC, sanxun0325 commented on clients/nacos_client/nacos_client.go
> +	"github.com/nacos-group/nacos-sdk-go/common/logger"
update the import format, using goimport,gofmt

2021-06-11 02:48 UTC, x-lambda commented
@sanxun0325 hi，请问这个pr还需要改进吗？

2021-06-11 03:16 UTC, sanxun0325 commented
Thank you for contribution

2021-06-11 03:17 UTC, merged