注入对日志接口的实现
nacos-group/nacos-sdk-go pull request #405
Opened 2022-02-14 03:05 UTC by habby-c

不知道这种方式可以不，外部注入一个对logger的实现，自定义的日志输出

2022-02-14 10:22 UTC, sanxun0325 reviewed
自定义log 这种方式没有问题

2022-02-14 10:30 UTC, sanxun0325 commented on clients/config_client/config_client_test.go
> +	"net/http"
导入的包顺序有问题

2022-02-14 10:30 UTC, sanxun0325 commented on clients/nacos_client/nacos_client.go
> +	//logger.Infof("logDir:<%s>   cacheDir:<%s>", config.LogDir, config.CacheDir)
为什么要删除日志

2022-02-14 10:30 UTC, sanxun0325 commented on common/constant/config.go
> +type Logger interface {
在common/logger 中有定义好的接口，这里不需要重新定义

2022-02-15 03:39 UTC, habby-c commented on clients/nacos_client/nacos_client.go
> +	//logger.Infof("logDir:<%s>   cacheDir:<%s>", config.LogDir, config.CacheDir)
会有一个循环导入的问题，但是貌似我迁移了位置之后就不会了

2022-02-15 03:40 UTC, habby-c commented
看到了你的答复我一波整理下

2022-02-25 08:02 UTC, HabbyChen commented
将日志改为可以外部注入
为了避免循环引入，将日志配置移入日志相关目录中。

2022-03-15 09:51 UTC, li-jin-gou commented
@HabbyChen  hello,我现在的开发也需要在`nacos-sdk-go` 中自定义`logger`,这个PR预计什么时候可以合入呢？
另外我还有两个问题:
是否也可以支持一下 `writer`和 `level` 的自定义呢？类似
```
type Control interface {
	SetLevel(Level)
	SetOutput(io.Writer)
}
```

2022-03-16 01:37 UTC, HabbyChen commented
> 

有几个测试没过，我争取这周吧

2022-03-17 12:20 UTC, SpecialYang requested changes

2022-03-17 12:20 UTC, SpecialYang commented on common/logger/logger.go
> +	MaxBackups int
I suggest the default MaxBackups is explicit value instead of infinity.

2022-03-17 12:20 UTC, SpecialYang commented on common/logger/logger.go
> +	MaxAge int
Same with MaxBackups.

2022-03-17 12:20 UTC, SpecialYang commented on common/constant/log.go
> +package constant
delete

2022-03-17 12:20 UTC, SpecialYang commented on common/constant/const.go
> +	LOG_FILE_NAME               = "./nacos-sdk.log"
Why need this prefix?

2022-03-17 12:20 UTC, SpecialYang commented on common/logger/logger.go
> +const LogFileName = "nacos-sdk.log"
Use LOG_FILE_NAME instead.

2022-03-17 12:20 UTC, SpecialYang commented on clients/config_client/config_client.go
> +		LogDir:                 "",
ClientConfig.LogDir

2022-03-21 07:34 UTC, realJackSun commented
@HabbyChen 这个修改有进展吗？如果你没有时间搞的话，我们可以帮你更正

2022-03-21 07:37 UTC, HabbyChen commented
> @HabbyChen 这个修改有进展吗？如果你没有时间搞的话，我们可以帮你更正

我本周内修正吧

2022-03-21 10:44 UTC, HabbyChen commented on common/constant/const.go
> +	LOG_FILE_NAME               = "./nacos-sdk.log"
如果说在没有定义路径的情况下，会因为没有nacos-sdk.log默认目录的权限而报错

2022-03-31 06:33 UTC, realJackSun approved these changes

2022-03-31 12:24 UTC, SpecialYang approved these changes

2022-03-31 12:36 UTC, merged

2022-08-16 09:18 UTC, YiuTerran commented
请添加相关文档和example，谢谢