修复监听配置时轮询频率过高导致的cpu占用过高问题
nacos-group/nacos-sdk-go pull request #561
Opened 2023-01-25 03:46 UTC by liang09255

使用v1的sdk时发现配置监听一启动就会有cpu占有率飙升的问题，后来看了看监听配置时每10毫秒都会去轮询一次配置信息，这个速度似乎有点过快了

2023-01-30 09:33 UTC, binbin0325 requested changes

2023-01-30 09:33 UTC, binbin0325 commented on clients/config_client/config_client.go
> +				go client.delayScheduler(time.NewTimer(1*time.Millisecond), 1*time.Second, strconv.Itoa(i), client.longPulling(i))
和NewConfigClient时保持一致吧，都是500毫秒

2023-01-31 03:36 UTC, wangdongyun commented
> 使用v1的sdk时发现配置监听一启动就会有cpu占有率飙升的问题，后来看了看监听配置时每10毫秒都会去轮询一次配置信息，这个速度似乎有点过快了

这个是因为 namespace 配置的不对吧！
客户端是不是显示设置了public 关键字

2023-01-31 06:06 UTC, liang09255 reviewed
Update config_client.go

2023-01-31 06:12 UTC, liang09255 commented
> > 使用v1的sdk时发现配置监听一启动就会有cpu占有率飙升的问题，后来看了看监听配置时每10毫秒都会去轮询一次配置信息，这个速度似乎有点过快了
> 
> 这个是因为 namespace 配置的不对吧！ 客户端是不是显示设置了public 关键字

没听太懂，具体讲讲？
我原本理解的就是会每500ms去检查一下有没有新的监听任务，如果有新的任务的话，再为新的监听任务开一个goroutine每10ms去对nacos进行轮询配置信息，看有没有变更，然后因为十毫秒这个间隔有点短了，每秒一百次请求导致cpu占用过高

2023-01-31 09:04 UTC, wangdongyun commented
这里是 长轮询机制，不会每10ms请求一次Nacos。

2023-01-31 10:01 UTC, chuntaojun commented
> > > 使用v1的sdk时发现配置监听一启动就会有cpu占有率飙升的问题，后来看了看监听配置时每10毫秒都会去轮询一次配置信息，这个速度似乎有点过快了
> > 
> > 
> > 这个是因为 namespace 配置的不对吧！ 客户端是不是显示设置了public 关键字
> 
> 没听太懂，具体讲讲？ 我原本理解的就是会每500ms去检查一下有没有新的监听任务，如果有新的任务的话，再为新的监听任务开一个goroutine每10ms去对nacos进行轮询配置信息，看有没有变更，然后因为十毫秒这个间隔有点短了，每秒一百次请求导致cpu占用过高

服务端没有变更的话，服务端会hold住连接30second，然后在返回给client，因此如果配置没有变更，这个任务的实际执行周期是 30second + 10millsecond

如果因为这个循环导致CPU升高，先看下是不是你的监听参数有问题

2023-01-31 13:38 UTC, closed without merging