调整 [INFO] logDir cacheDir 日志输出
nacos-group/nacos-sdk-go pull request #590
Opened 2023-03-16 10:46 UTC by Cotch22

https://github.com/nacos-group/nacos-sdk-go/issues/260

这个问题曾经被提到过，但是在一次次更变中又被改了回去。

go 的默认 log 是 StdErr 通道的，这条日志打印对日志收集器存在影响。

现在改为 日志等级为 info 时才打印，并且打印到 StdOut标准输出。

2023-03-16 13:00 UTC, binbin0325 requested changes

2023-03-16 13:00 UTC, binbin0325 commented on clients/nacos_client/nacos_client.go
> -	log.Printf("[INFO] logDir:<%s>   cacheDir:<%s>", config.LogDir, config.CacheDir)
log.Printf 可以替换为使用logger.Infof打印

2023-03-16 13:05 UTC, Cotch22 commented on clients/nacos_client/nacos_client.go
> -	log.Printf("[INFO] logDir:<%s>   cacheDir:<%s>", config.LogDir, config.CacheDir)
在 https://github.com/nacos-group/nacos-sdk-go/issues/260 当中最后确实用 logger 替换了，但之后的更新中又把logger包去掉了，并且将这行注释，不知道当时的意图
最终又用回了 log 打印，所以这里要改成logger吗

2023-03-16 13:07 UTC, Cotch22 commented
> > #260
> > 这个问题曾经被提到过，但是在一次次更变中又被改了回去。
> > go 的默认 log 是 StdErr 通道的，这条日志打印对日志收集器存在影响。
> > 现在改为 日志等级为 info 时才打印，并且打印到 StdOut标准输出。
> 
> 存在的影响是什么？可以具体一点吗？

很简单，因为 log 默认输出到了 StdErr，会被日志采集器采集，我们一些任务脚本会检测到标准错误输出，然后给任务标记为出错

2023-03-18 06:20 UTC, binbin0325 commented on clients/nacos_client/nacos_client.go
> +	if config.LogLevel == "info" {
这里不应该是只有info级别时打印，如果增加判断，还需要考虑日志级别。  
默认logger是debug级别，去掉判断，直接打印出来就好。

2023-03-20 02:05 UTC, binbin0325 approved these changes

2023-03-20 02:14 UTC, binbin0325 commented on clients/nacos_client/nacos_client.go
> +	"github.com/nacos-group/nacos-sdk-go/common/logger"
修复CI，导入v2版本logger

2023-03-23 01:54 UTC, merged