fix: remove unsupported parameters in the README.md
nacos-group/nacos-sdk-go pull request #663
Opened 2023-10-07 07:30 UTC by palp1tate

2023-10-08 02:33 UTC, binbin0325 reviewed
Fields such as LogSampling、LogRollingConfig can be updated

2023-10-08 05:56 UTC, palp1tate commented
> Fields such as LogSampling、LogRollingConfig can be updated



> Fields such as LogSampling、LogRollingConfig can be updated

I have resubmitted the PR according to your requirement.Please review.

2023-10-23 13:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nacos-group/nacos-sdk-go?pullRequest=663) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nacos-group/nacos-sdk-go?pullRequest=663) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nacos-group/nacos-sdk-go?pullRequest=663) it.</sub>

2023-11-08 11:49 UTC, binbin0325 requested changes
adjust indent

2023-11-08 13:15 UTC, closed without merging