Fix InitLogger just no work
nacos-group/nacos-sdk-go pull request #759
Opened 2024-06-06 20:28 UTC by dingyang666

https://github.com/nacos-group/nacos-sdk-go/pull/722 这个 pr 导致 InitLogger 无法工作，原因是 init 创建了一个 logger 导致  InitLogger 中的 if logger != nil 永远是 true，见 https://github.com/nacos-group/nacos-sdk-go/issues/747

碰巧 init 中创建的 logger 是 debug 级别，会在线上输出大量日志
![image](https://github.com/nacos-group/nacos-sdk-go/assets/46430061/4f7a1d59-7454-4b34-9781-7144b806aabd)

改用 sync.Once 保证只创建一次的同时，在 InitLogger 不失效的同时，满足 https://github.com/nacos-group/nacos-sdk-go/pull/722 老哥大量创建和销毁客户端的奇怪需求

2024-06-06 20:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nacos-group/nacos-sdk-go?pullRequest=759) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nacos-group/nacos-sdk-go?pullRequest=759) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nacos-group/nacos-sdk-go?pullRequest=759) it.</sub>

2024-06-12 02:09 UTC, binbin0325 requested changes
建议直接去掉 logger != nil 的逻辑，这里应该允许重复创建logger， 大量创建使用不当，不应该在sdk的考虑范围内

2024-06-12 02:15 UTC, dingyang666 commented
> 建议直接去掉 logger != nil 的逻辑，这里应该允许重复创建logger， 大量创建使用不当，不应该在sdk的考虑范围内

done

2024-06-13 01:43 UTC, binbin0325 approved these changes
LGTM

2024-06-13 01:43 UTC, merged