Fix refresh listen
nacos-group/nacos-sdk-go pull request #789
Opened 2024-12-31 09:51 UTC by tclxjing8-li

executeConfigListen when rpc client reconnect

2024-12-31 09:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nacos-group/nacos-sdk-go?pullRequest=789) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nacos-group/nacos-sdk-go?pullRequest=789) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nacos-group/nacos-sdk-go?pullRequest=789) it.</sub>

2024-12-31 10:10 UTC, tclxjing8-li commented
当网络出现异常，例如客户端和服务端网络中断2分钟，期间服务端配置发生变更，在网络恢复之后，客户端并没有及时发送ConfigBatchListenRequest，导致客户端配置会出现分钟级的延迟

2025-01-21 08:57 UTC, binbin0325 approved these changes
LGTM

2025-01-21 09:04 UTC, binbin0325 requested changes

2025-01-21 09:04 UTC, binbin0325 commented on common/remote/rpc/rpc_client.go
> +			ReconnectionChan <- struct{}{}
也许不需要ReconnectionChan，可以看下在notifyConnectionChange中实现IConnectionEventListener接口。

2025-01-22 02:31 UTC, closed without merging

2025-01-22 11:03 UTC, tclxjing8-li commented on common/remote/rpc/rpc_client.go
> +			ReconnectionChan <- struct{}{}
IConnectionEventListener也是通过RpcClient.eventChan通知连接状态的变更，config订阅这边同样用了ReconnectionChan来触发ConfigClient的executeConfigListen，应该也可以吧？